In [2]:
import numpy as np

## Broadcast

In [48]:
a1=np.array([[1,2,3],[4,5,6],[7,8,9]])
a2=np.array([1,2,3])

In [50]:
a1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [51]:
a2

array([1, 2, 3])

In [52]:
a1+a2

array([[ 2,  4,  6],
       [ 5,  7,  9],
       [ 8, 10, 12]])

In [53]:
aa = np.array((0,10,20,30))
bb = np.array((0,1,2))
y = aa[:, None] + bb

print(y)

[[ 0  1  2]
 [10 11 12]
 [20 21 22]
 [30 31 32]]


In [54]:
aa[:, None]

array([[ 0],
       [10],
       [20],
       [30]])

In [55]:
aa.reshape(4,1)

array([[ 0],
       [10],
       [20],
       [30]])

## Custom type

In [16]:
dt = np.dtype("i4,f8,a5")
print (dt.fields)
a =np.array([(1,2.0,"Hello"), (2,3.0,"World")], dtype=dt)
print (a)
a[0]

{'f0': (dtype('int32'), 0), 'f1': (dtype('float64'), 4), 'f2': (dtype('S5'), 12)}
[(1, 2., b'Hello') (2, 3., b'World')]


(1, 2., b'Hello')

In [18]:
a['f2']

array([b'Hello', b'World'], dtype='|S5')

In [20]:
a.nbytes

34

## Object type

In [12]:
class Complex(object):
    def __init__(self,real = 0,img = 0):
        self.__real = real
        self.__img = img
    def __add__(self,b):
        res = Complex(self.__real +b.__real, self.__img + b.__img)
        return res
    def __str__(self):
        if(self.__img >=0):
            str1 = " + "
            num = self.__img
        else:
            str1 = " - "
            num = self.__img * -1
        st = ("Complex " + str(self.__real) + 
                    str1 + str(num) + "i ")
        return st

    
a = Complex(10,-20)
b = Complex(9,7)


aa = np.array([a, b], Complex)
bb = np.array([a, b], Complex)
v=aa+bb
print(v[0])

Complex 20 - 40i 


# Working with files

In [21]:
arr = np.random.rand(4,5)

In [22]:
arr

array([[0.87209087, 0.79660222, 0.95024397, 0.70951427, 0.19970373],
       [0.93728231, 0.37697078, 0.46127295, 0.36383287, 0.60578782],
       [0.033583  , 0.60634322, 0.58457089, 0.63737201, 0.63682605],
       [0.43001376, 0.0669687 , 0.95222784, 0.6389528 , 0.3694128 ]])

In [23]:
np.save("data1",arr)
np.savetxt("data1.txt",arr)

In [24]:
arr2=np.load("data1.npy")

In [25]:
arr2

array([[0.87209087, 0.79660222, 0.95024397, 0.70951427, 0.19970373],
       [0.93728231, 0.37697078, 0.46127295, 0.36383287, 0.60578782],
       [0.033583  , 0.60634322, 0.58457089, 0.63737201, 0.63682605],
       [0.43001376, 0.0669687 , 0.95222784, 0.6389528 , 0.3694128 ]])

In [26]:
arr3 = np.loadtxt("data1.txt")

In [27]:
arr3

array([[0.87209087, 0.79660222, 0.95024397, 0.70951427, 0.19970373],
       [0.93728231, 0.37697078, 0.46127295, 0.36383287, 0.60578782],
       [0.033583  , 0.60634322, 0.58457089, 0.63737201, 0.63682605],
       [0.43001376, 0.0669687 , 0.95222784, 0.6389528 , 0.3694128 ]])

## Indexing Tricks

In [28]:
s=np.lib.index_tricks.RClass()
print (s)

In [29]:
print (s[0])

[0]


In [30]:
print (s[1])

[1]


In [31]:
print (s[1:20])

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [32]:
print (s[1:20:2])

[ 1  3  5  7  9 11 13 15 17 19]


In [33]:
print (s[1:20:2j])

[ 1. 20.]


In [34]:
print (s[1:20:20j])

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17. 18.
 19. 20.]


In [36]:
print (s[1:5:10j])

[1.         1.44444444 1.88888889 2.33333333 2.77777778 3.22222222
 3.66666667 4.11111111 4.55555556 5.        ]


In [25]:
s[1:3,5:8]

array([1, 2, 5, 6, 7])

In [26]:
s[2:4,5:15:2,20:22]

array([ 2,  3,  5,  7,  9, 11, 13, 20, 21])

In [27]:
s[2:4,5:15:20j,20:22]

array([ 2.        ,  3.        ,  5.        ,  5.52631579,  6.05263158,
        6.57894737,  7.10526316,  7.63157895,  8.15789474,  8.68421053,
        9.21052632,  9.73684211, 10.26315789, 10.78947368, 11.31578947,
       11.84210526, 12.36842105, 12.89473684, 13.42105263, 13.94736842,
       14.47368421, 15.        , 20.        , 21.        ])

<br/><br/>
## Views

In [45]:
a = np.array([[0, 4, 5, 8],
              [1, 4, 5, 8],
              [1, 4, 5, 8],
              [1, 4, 5, 8]],'i1')
              
b = a.view('i4')

d=[hex(val.item()) for val in b.flat]
print(d)

['0x8050400', '0x8050401', '0x8050401', '0x8050401']


In [46]:
b

array([[134546432],
       [134546433],
       [134546433],
       [134546433]], dtype=int32)

In [47]:
a.tobytes()

b'\x00\x04\x05\x08\x01\x04\x05\x08\x01\x04\x05\x08\x01\x04\x05\x08'

In [48]:
b.tobytes()

b'\x00\x04\x05\x08\x01\x04\x05\x08\x01\x04\x05\x08\x01\x04\x05\x08'

<br><br><br>
## Universal functions

In [28]:
a=np.array([1,2,3])
b=np.array([3,4,5])

c = np.add.__call__(a,b)
print(c)

[4 6 8]


In [29]:
a+b

array([4, 6, 8])

In [30]:
np.add(a,b)

array([4, 6, 8])

In [31]:
a

array([1, 2, 3])

In [51]:
np.add.accumulate(a)

array([1, 3, 6])

In [52]:
x = np.array([[1, 5, 6, 10], [0, 6, 16, 8]])

In [53]:
x

array([[ 1,  5,  6, 10],
       [ 0,  6, 16,  8]])

In [57]:
np.add.accumulate(x)

array([[ 1,  5,  6, 10],
       [ 1, 11, 22, 18]])

In [58]:
np.add.accumulate(x,axis=1)

array([[ 1,  6, 12, 22],
       [ 0,  6, 22, 30]])

## diff

In [32]:
x = np.array([[1, 5, 6, 10], [0, 6, 16, 8],[2,10,10,9]])
x

array([[ 1,  5,  6, 10],
       [ 0,  6, 16,  8],
       [ 2, 10, 10,  9]])

In [64]:
np.diff(x)

array([[ 4,  1,  4],
       [ 6, 10, -8],
       [ 8,  0, -1]])

In [65]:
np.diff(x, axis=0)

array([[-1,  1, 10, -2],
       [ 2,  4, -6,  1]])

## masking

In [36]:
x[x>8]=100

In [37]:
x

array([[  1,   5,   6, 100],
       [  0,   6, 100,   8],
       [  2, 100, 100, 100]])

In [38]:
a=np.random.randint(0,2,(4,5))

a[a==0]=100

In [39]:
a==100

array([[ True, False, False, False, False],
       [ True,  True,  True,  True, False],
       [False,  True, False, False, False],
       [False,  True,  True,  True,  True]])

In [40]:
a

array([[100,   1,   1,   1,   1],
       [100, 100, 100, 100,   1],
       [  1, 100,   1,   1,   1],
       [  1, 100, 100, 100, 100]])

In [43]:
b=np.random.randint(5,11,(4,5))

c=np.where(a==100,b,a)

In [44]:
b

array([[ 9, 10,  8,  8,  9],
       [ 9, 10,  7,  6,  8],
       [ 6,  8,  7,  5, 10],
       [ 8,  5, 10,  9,  9]])

In [71]:
c

array([[  7,   5,  10,   7,   5],
       [  5,   7,   5,   6, 100],
       [ 10, 100, 100, 100,   8],
       [ 10,   9, 100, 100, 100]])

# Linear algebra

In [57]:
a = np.arange(1,10).reshape(3,3)

In [58]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [59]:
np.linalg.det(a)

-9.51619735392994e-16

In [60]:
np.linalg.inv(a)

array([[ 3.15251974e+15, -6.30503948e+15,  3.15251974e+15],
       [-6.30503948e+15,  1.26100790e+16, -6.30503948e+15],
       [ 3.15251974e+15, -6.30503948e+15,  3.15251974e+15]])

In [61]:
a1 = np.array([[1,2],[3,4]])

In [62]:
b1=np.array([5,11])

In [63]:
np.linalg.solve(a1,b1)

array([1., 2.])