In [2]:
import numpy as np
import matplotlib.pyplot as plt

In [21]:
arr=np.arange(1,10).reshape(3,3)

In [22]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [24]:
b1=arr[ 1: , ::2]

In [25]:
b1

array([[4, 6],
       [7, 9]])

In [26]:
b1[0,0] = 1000

In [27]:
arr

array([[   1,    2,    3],
       [1000,    5,    6],
       [   7,    8,    9]])

In [5]:
arr[0]

array([1, 2, 3])

In [6]:
arr[0][1]

2

In [7]:
arr[0,1]

2

In [28]:
arr=np.arange(10,20)

In [17]:
arr

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [18]:
arr[1:4]

array([11, 12, 13])

In [19]:
arr[4:1:-2]

array([14, 12])

In [20]:
arr[::-2]

array([19, 17, 15, 13, 11])

In [29]:
arr

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [31]:
b=arr[ [1,3,4,7 ]  ]

In [32]:
b[0]=9999

In [33]:
arr

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [34]:
arr[ [1,3,4,7 ]  ]*=10

In [35]:
arr

array([ 10, 110,  12, 130, 140,  15,  16, 170,  18,  19])

In [36]:
a=np.array([1,2,3],dtype=np.uint)

In [37]:
a1=np.array([1,2,3,4])

In [38]:
np.sum(a1)

10

In [39]:
np.sum(a1*a1)

30

In [40]:
a1.min()

1

In [41]:
np.min(a1)

1

In [42]:
a1=np.random.randint(1,30,(4,5))

In [43]:
a1

array([[12,  1, 16, 27, 29],
       [24,  2, 18,  3, 20],
       [ 6, 21, 10, 23,  3],
       [ 1, 15, 16, 25, 16]])

In [48]:
a1.min(axis=0)

array([ 1,  1, 10,  3,  3])

In [49]:
np.sum(a1[0])

85

In [59]:
a = np.array([[1,2,3],
               [40,5,8]], float)


In [60]:
a

array([[ 1.,  2.,  3.],
       [40.,  5.,  8.]])

In [57]:
np.average(a,weights=[1,2,3],axis=1)

array([2.33333333, 5.33333333])

In [61]:
a.ptp(axis=0)

array([39.,  3.,  5.])

In [62]:
np.pi

3.141592653589793

In [63]:
np.e

2.718281828459045